### ISSUE TITLE
Durabilité des items

### ISSUE THREAD

**Issue by morshey77** [Plutonium-Mcpe/pluto-wiki#32]
Etant donné l'importance de la durabilité, je crée cette issue afin qu'il soit renseigné sur chaque élément en possédant une, de manière à mieux nous guider pour éviter tout cassure.

Merci d'avoir pris le temps de lire.

**Comment by ShockedPlot7560** [comment]
Bonjour,
Quel sont les articles concernés ? 
Je sais que les outils vont être effectué, ils n'ont juste pas été mis à jour. 
Peut être les armures ? Les items PvP ? 
Si c'est cela, ca sera fzit dans les jour prochains.

**Comment by morshey77** [comment]
Bonsoir, 
"Quel sont les articles concernés ?", c'est votre wiki donc je ne peux pas savoir mieux que vous. Tous les elements que vous décider de mettre dans le wiki, qui possède l'attribut durabilité doivent être renseigné pour un wiki opérationnel.

**Comment by ShockedPlot7560** [comment]
En effet, ca sera mit en place au plus vite.
Merci, vous serez tenu informé de la situation ici.

**Comment by ShockedPlot7560** [comment]
- [x] Vérifier les bâtons de soins
- [x] Mettre à jour les unclaim finders
- [x] Mettre durabilité maximale brouilleur
- [x] Armure de farm

**Comment by ShockedPlot7560** [comment]
Tout les items ont été vérifiées, les modifications seront disponibles prochainement.
