### ISSUE TITLE
Modification métier de guerrier (xp)

### ISSUE THREAD

**Issue by Clemspskyrim69** [Plutonium-Mcpe/pluto-wiki#34]
Bonjour, j'ai remarqué sur le wiki du métier de guerrier que l'xp n'était pas à jour comparé à l'information ingame

**Sur le wiki :**

- Tue un joueur : 10 XP
- araignée : 0.05 XP
- Zombie : 0.05 XP
- Creeper : 0.05 XP
- Squelette : 0.05 XP
- Mouton : 0.05 XP

**Sur le jeu ig:**

- Tue un joueur : 15 XP
- araignée : 0.1 XP
- Zombie : 0.1 XP
- Creeper : 0.1 XP
- Squelette : 0.1  XP
- Mouton : 0.1  XP

Bonne modif :)

**Comment by ShockedPlot7560** [comment]
Merci pour le report,
Ceci a été modifié et sera disponible sur le site prochainement.
