### ISSUE TITLE
Erreur métier Epée en opalite

### ISSUE THREAD

**Issue by ShockedPlot7560** [Plutonium-Mcpe/pluto-wiki#54]
Il est notifié qu'il faut être niveau 93 dans le métier de bûcheron pour obtenir l'épée en opalite

**Comment by xEditedNewt** [comment]
Heu j'ai check, je n'ai pas trouvé

**Comment by ShockedPlot7560** [comment]
https://www.plutonium.best/wiki/tools/sword
 
![image](https://user-images.githubusercontent.com/66992287/192019127-26cfc6aa-bf52-4e06-8bd8-707cf0a6bfce.png)

**Comment by xEditedNewt** [comment]
Ok je modifie ca

**Comment by ShockedPlot7560** [comment]
- fixed by #66
