### ISSUE TITLE
Image du ballon de foot bugé

### ISSUE THREAD

**Issue by ShockedPlot7560** [Plutonium-Mcpe/pluto-wiki#58]
L'image d'illustration du ballon de foot n'est pas trouvé et ainsi est bugé.  
https://www.plutonium.best/wiki/items/ball

**Comment by ghost** [comment]
ok,

**Comment by ghost** [comment]
mais c'est celle sur twitter ?

**Comment by ShockedPlot7560** [comment]
Celle du pack directement normalement

**Comment by xEditedNewt** [comment]
Normalement terminé

**Comment by CubeHugo** [comment]
Ok
